// Generated by scripts/prepare-drawings.mjs. Do not edit by hand.
// Doodle names that have a hand-drawn PNG in /public/doodles.
export const DRAWN = new Set<string>([
  "empty-kept",
  "empty-lessons",
  "empty-notebook",
  "empty-today",
  "kept",
  "logo",
  "logo-small",
  "nav-kept",
  "nav-notebooks",
  "nav-today",
  "nav-you-two",
  "nb-cooking",
  "nb-language",
  "nb-music",
  "nb-popcorn",
  "nb-reading",
  "stars"
]);
